### ISSUE TITLE
UNVTPortableワークショップ 2023.06.03 @青山キャンパスについて

### ISSUE THREAD

**Issue by ShogoHirasawa** [unvt/portable#18]
## タスク
- [x] Peatixの概要文章作成
- [x] Peatixのサムネイル作成
- [x] 当日タイムラインの作成
- [x] スライドの作成

## 持ち物リスト
- [x] 参加者の人数分のLANケーブル
- [x] Raspberry Pi （平澤2台.古橋先生3台）

## スライド
https://docs.google.com/presentation/d/16eikB3bkCCmo7tIcwS_DY1ICMUuMLXUVyyaLM1wqTuI/edit?usp=sharing

**Comment by ShogoHirasawa** [comment]
## peatix文章案

Raspberry Piを利用したオフラインWeb地図サーバー「UNVT Portable」のワークショップを開催いたします。
「UNVT Portable」は、国連のUN Open GIS Initiativeに採択された公式プロジェクトです。このプロジェクトでは、ハードウェア、ソフトウェア、利用する地理データのすべてをオープンソースで構成しています。

現代社会では、インターネットを介して地図を閲覧することが当たり前となっていますが、オフライン環境下でも地図システムを利用できるニーズは日増しに高まっています。発展途上国や災害発生直後など、インターネットインフラが整備されていない状況でも、「UNVT Portable」を活用することで地図を閲覧することができます。

当ワークショップでは、「UNVT Portable」の制作背景や、具体的な技術について詳しく説明いたします。さらに、実際の実装方法についても丁寧にご説明いたします。

お時間のある方は、ぜひ会場まで足を運んでいただき、ワークショップにご参加ください。

**Comment by ShogoHirasawa** [comment]
## データ一覧
`関東のOSMのベクトルタイル`
https://github.com/ShogoHirasawa/Kanto_basemap/tree/main/zxy
`東京都の避難所データ`

**Comment by ShogoHirasawa** [comment]
## タイムライン
09:30 会場
10:00 ワークショップ（前半）スタート
12:00 ランチタイム
13:30 ワークショップ（後半）スタート
15:00 ワークショップ終了
15:10 記念撮影 and 自由時間
18:00 交流会スタート
20:00 解散

**Comment by ShogoHirasawa** [comment]
## wikiデータの改修
現行のwikiに書いてあるチュートリアルだと途中でコケることが発覚。
wiki ver2.0を作成した。（2023/05/26時点でまだ調整中...）
[UNVTPortable_wiki.md](https://github.com/unvt/portable/files/11573221/UNVTPortable_wiki.md)

**Comment by ShogoHirasawa** [comment]
## ワークショップでの気づき
-

**Comment by mapconcierge** [comment]
# 今回の作業環境MEMO
 * RaspberryPi OS インストール： imager_1.7.5.dmg を使用
